// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nljhbmgbgqqcaxqbvghs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5samhibWdiZ3FxY2F4cWJ2Z2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODQzNDcsImV4cCI6MjA2MjA2MDM0N30.F6BrsaBMErZl-H5uTnt3QT37r_Qsx8Izg0ro1HQyyEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);