// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edzxpaihgygkhdphdsyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkenhwYWloZ3lna2hkcGhkc3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODE1ODIsImV4cCI6MjA2NjQ1NzU4Mn0.I9WU3pCkHigqun0UvSs-olnJtAtU3OUHwK__jAKsCwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);